version: '3.0'
services: 
  api:
    image: 533545012068.dkr.ecr.ap-southeast-2.amazonaws.com/demo-verifier-agent:latest 
    environment: 
      PORT: 80
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-verifier
        awslogs-region: ap-southeast-2
        awslogs-stream: demo-verifier-agent-latest
  verifier:
    image: 533545012068.dkr.ecr.ap-southeast-2.amazonaws.com/demo-verifier:latest 
    environment: 
      PORT: 80
  nginx:
    image: 533545012068.dkr.ecr.ap-southeast-2.amazonaws.com/demo-verifier-nginx:latest
    ports:
      - 80:80
    depends_on:
      - verifier
      - api